export const storeProducts = [
  {
    id: 1,
    title: "SPOR INTERIOR",
    img: "img/sporinterior.png",
    price: 150,
    company: "SPOR",
    info: "Alb generos rezistent 5 ani Nu curge si nu stropeste in timpul vopsirii Acopera perfect",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "SPOR EXTERIOR ",
    img: "img/sporexterior.jpg",
    price: 160,
    company: "SPOR",
    info: "Vopsea lavabila pentru exterior cu silicon Protejeaza fatadele cladirilor impotriva factorilor climatici Rezistenta vizibila in timp Putere mare de acoperire",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "SPOR CU IONI DE ARGINT",
    img: "img/sporioniargint.jpg",
    price: 155,
    company: "SPOR",
    info: "Vopsea superlavabila pentru interior cu ioni de argint Efect antibacterian si antifungicSuperputere de acoperire Produs avizat de Ministerul Sanatatii, asigura un climat sanatos ",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "SPOR BAIE SI BUCATARIE",
    img: "img/sporbaie.jpg",
    price: 155,
    company: "SPOR",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "SPOR BAZA NUANTARE",
    img: "img/sporbazanuantare.jpg",
    price: 170,
    company: "SPOR",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "CASA BELLA INTERIOR",
    img: "img/casainterior.png",
    price: 70,
    company: "apple",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "CASA BELLA EMAIL LUCIOS",
    img: "img/casacolor.jpg",
    price: 22,
    company: "apple",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "CASA BELLA LAC LEMN",
    img: "img/casalac.jpg",
    price: 22,
    company: "apple",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "SPOR INTERIOR",
  img: "img/sporinterior.png",
  price: 150,
  company: "SPOR",
  info: "Alb generos rezistent 5 ani Nu curge si nu stropeste in timpul vopsirii Acopera perfect",
  inCart: false,
  count: 0,
  total: 0,
};
